"""empty message

Revision ID: 9f246abd7693
Revises: 0a6dd81ef089
Create Date: 2024-09-02 08:14:45.056150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f246abd7693'
down_revision = '0a6dd81ef089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=126), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=126), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
